// Code generated by github.com/ONDC-Official/automation-validation-compiler, DO NOT EDIT.

package storageutils

import (
	"encoding/json"
	"fmt"
	"time"
	"validationpkg/validationutils"
)

// saveFunction saves extracted data from payload to storage
func saveFunction(
	payload interface{},
	uniquePrefix string,
	key string,
	path string,
	store validationutils.StorageInterface,
	config StorageConfig,
	action string,
) error {
	if path == "" || key == "_SELF" {
		return nil
	}

	// Extract value using JSONPath
	value := validationutils.GetJsonPath(payload, path, true)

	// Create data structure
	data := map[string]interface{}{
		"stored_from": action + "_action",
		"key_path":    path,
		"value":       value,
		"timestamp":   time.Now().UTC().Format(time.RFC3339),
	}

	// Serialize to JSON
	dataBytes, err := json.Marshal(data)
	if err != nil {
		return fmt.Errorf("failed to marshal data: %w", err)
	}

	// Save with retry logic
	return SaveData(uniquePrefix, key, string(dataBytes), store, config)
}

// loadFunction loads and parses stored data from storage
func loadFunction(
	store validationutils.StorageInterface,
	uniquePrefix string,
	key string,
) ([]string, error) {
	value, err := store.GetKey(uniquePrefix, key)
	if err != nil {
		// Return empty slice on error (matches TS behavior)
		return []string{}, nil
	}

	if value == "" {
		return []string{}, nil
	}

	// Parse JSON
	var data struct {
		Value []interface{} `json:"value"`
	}

	if err := json.Unmarshal([]byte(value), &data); err != nil {
		return []string{}, nil
	}

	// Convert to string slice
	result := make([]string, 0, len(data.Value))
	for _, v := range data.Value {
		if v == nil {
			result = append(result, "null")
		} else {
			result = append(result, fmt.Sprintf("%v", v))
		}
	}

	return result, nil
}
