// Code generated by github.com/ONDC-Official/automation-validation-compiler, DO NOT EDIT.

package storageutils

import (
	"fmt"
	"validationpkg/validationutils"
)

// Store_cancel stores data from payload to storage for the cancel action
func Store_cancel(
	uniquePrefix string,
	payload interface{},
	store validationutils.StorageInterface,
	config StorageConfig,
) error {
	fmt.Printf("Stored data for action cancel successfully\n")
	return nil
}

// LoadFor_cancel loads stored data for the cancel action
func LoadFor_cancel(
	uniquePrefix string,
	store validationutils.StorageInterface,
) (validationutils.ExternalData, error) {
	result := validationutils.ExternalData{}

	fmt.Printf("Loaded external data for action cancel: %+v\n", result)
	return result, nil
}
