// Code generated by github.com/ONDC-Official/automation-validation-compiler, DO NOT EDIT.
package storageutils

import (
	"fmt"
	"validationpkg/validationutils"
)

// PerformL1validationsSave saves validation state data for a given action
//
// Parameters:
//   - action: The action name
//   - uniquePrefix: Unique namespace prefix
//   - payload: The payload data to extract and save
//   - store: Storage interface implementation
//   - config: Optional storage configuration (nil uses defaults)
//
// Returns error if the action is not found or save fails
func PerformL1validationsSave(
	action string,
	uniquePrefix string,
	payload interface{},
	store validationutils.StorageInterface,
	config *StorageConfig,
) error {
	// Set default config if not provided
	completeConfig := StorageConfig{
		RetryAttempts: 3,
		RetryDelayMs:  1000,
	}

	if config != nil {
		if config.RetryAttempts > 0 {
			completeConfig.RetryAttempts = config.RetryAttempts
		}
		if config.RetryDelayMs > 0 {
			completeConfig.RetryDelayMs = config.RetryDelayMs
		}
	}

	switch action {
	case "search":
		return Store_search(uniquePrefix, payload, store, completeConfig)
	case "on_search":
		return Store_on_search(uniquePrefix, payload, store, completeConfig)
	case "select":
		return Store_select(uniquePrefix, payload, store, completeConfig)
	case "on_select":
		return Store_on_select(uniquePrefix, payload, store, completeConfig)
	case "init":
		return Store_init(uniquePrefix, payload, store, completeConfig)
	case "on_init":
		return Store_on_init(uniquePrefix, payload, store, completeConfig)
	case "confirm":
		return Store_confirm(uniquePrefix, payload, store, completeConfig)
	case "on_confirm":
		return Store_on_confirm(uniquePrefix, payload, store, completeConfig)
	case "status":
		return Store_status(uniquePrefix, payload, store, completeConfig)
	case "on_status":
		return Store_on_status(uniquePrefix, payload, store, completeConfig)
	case "update":
		return Store_update(uniquePrefix, payload, store, completeConfig)
	case "track":
		return Store_track(uniquePrefix, payload, store, completeConfig)
	case "on_track":
		return Store_on_track(uniquePrefix, payload, store, completeConfig)
	case "cancel":
		return Store_cancel(uniquePrefix, payload, store, completeConfig)
	case "on_cancel":
		return Store_on_cancel(uniquePrefix, payload, store, completeConfig)
	case "issue":
		return Store_issue(uniquePrefix, payload, store, completeConfig)
	case "on_issue":
		return Store_on_issue(uniquePrefix, payload, store, completeConfig)
	case "on_issue_status":
		return Store_on_issue_status(uniquePrefix, payload, store, completeConfig)
	case "on_update":
		return Store_on_update(uniquePrefix, payload, store, completeConfig)
	default:
		return fmt.Errorf("action not found: %s", action)
	}
}

// PerformL1validationsLoad loads validation state data for a given action
//
// Parameters:
//   - action: The action name
//   - uniquePrefix: Unique namespace prefix
//   - store: Storage interface implementation
//
// Returns ExternalData with loaded values and error if action not found
func PerformL1validationsLoad(
	action string,
	uniquePrefix string,
	store validationutils.StorageInterface,
) (validationutils.ExternalData, error) {
	switch action {
	case "search":
		return LoadFor_search(uniquePrefix, store)
	case "on_search":
		return LoadFor_on_search(uniquePrefix, store)
	case "select":
		return LoadFor_select(uniquePrefix, store)
	case "on_select":
		return LoadFor_on_select(uniquePrefix, store)
	case "init":
		return LoadFor_init(uniquePrefix, store)
	case "on_init":
		return LoadFor_on_init(uniquePrefix, store)
	case "confirm":
		return LoadFor_confirm(uniquePrefix, store)
	case "on_confirm":
		return LoadFor_on_confirm(uniquePrefix, store)
	case "status":
		return LoadFor_status(uniquePrefix, store)
	case "on_status":
		return LoadFor_on_status(uniquePrefix, store)
	case "update":
		return LoadFor_update(uniquePrefix, store)
	case "track":
		return LoadFor_track(uniquePrefix, store)
	case "on_track":
		return LoadFor_on_track(uniquePrefix, store)
	case "cancel":
		return LoadFor_cancel(uniquePrefix, store)
	case "on_cancel":
		return LoadFor_on_cancel(uniquePrefix, store)
	case "issue":
		return LoadFor_issue(uniquePrefix, store)
	case "on_issue":
		return LoadFor_on_issue(uniquePrefix, store)
	case "on_issue_status":
		return LoadFor_on_issue_status(uniquePrefix, store)
	case "on_update":
		return LoadFor_on_update(uniquePrefix, store)
	default:
		return validationutils.ExternalData{}, fmt.Errorf("action not found: %s", action)
	}
}
