// Code generated by github.com/ONDC-Official/automation-validation-compiler, DO NOT EDIT.

package storageutils

import (
	"fmt"
	"validationpkg/validationutils"
)

// Store_issue stores data from payload to storage for the issue action
func Store_issue(
	uniquePrefix string,
	payload interface{},
	store validationutils.StorageInterface,
	config StorageConfig,
) error {
	fmt.Printf("Stored data for action issue successfully\n")
	return nil
}

// LoadFor_issue loads stored data for the issue action
func LoadFor_issue(
	uniquePrefix string,
	store validationutils.StorageInterface,
) (validationutils.ExternalData, error) {
	result := validationutils.ExternalData{}

	fmt.Printf("Loaded external data for action issue: %+v\n", result)
	return result, nil
}
