// Code generated by github.com/ONDC-Official/automation-validation-compiler, DO NOT EDIT.

package storageutils

import (
	"fmt"
	"validationpkg/validationutils"
)

// Store_on_cancel stores data from payload to storage for the on_cancel action
func Store_on_cancel(
	uniquePrefix string,
	payload interface{},
	store validationutils.StorageInterface,
	config StorageConfig,
) error {
	fmt.Printf("Stored data for action on_cancel successfully\n")
	return nil
}

// LoadFor_on_cancel loads stored data for the on_cancel action
func LoadFor_on_cancel(
	uniquePrefix string,
	store validationutils.StorageInterface,
) (validationutils.ExternalData, error) {
	result := validationutils.ExternalData{}

	fmt.Printf("Loaded external data for action on_cancel: %+v\n", result)
	return result, nil
}
