// Code generated by github.com/ONDC-Official/automation-validation-compiler, DO NOT EDIT.

package storageutils

import (
	"fmt"
	"time"
	"validationpkg/validationutils"
)

// StorageConfig holds configuration for storage operations
type StorageConfig struct {
	// RetryAttempts is the number of times to retry a failed operation
	RetryAttempts int
	// RetryDelayMs is the delay in milliseconds between retry attempts
	RetryDelayMs int
}

// DefaultStorageConfig returns a StorageConfig with sensible defaults
func DefaultStorageConfig() StorageConfig {
	return StorageConfig{
		RetryAttempts: 3,
		RetryDelayMs:  100,
	}
}

// SaveData saves data to storage with retry logic
//
// Parameters:
//   - uniquePrefix: The namespace prefix for the key
//   - key: The key to store the data under
//   - saveData: The string data to save
//   - store: The storage interface implementation
//   - config: Configuration including retry settings
//
// Returns error if all retry attempts fail
func SaveData(
	uniquePrefix string,
	key string,
	saveData string,
	store validationutils.StorageInterface,
	config StorageConfig,
) error {
	finalKey := key
	retryTimes := config.RetryAttempts
	delayMs := config.RetryDelayMs
	attempts := 0

	for attempts < retryTimes {
		err := store.SaveKey(uniquePrefix, finalKey, saveData)
		if err == nil {
			return nil
		}

		attempts++
		if attempts >= retryTimes {
			return fmt.Errorf("failed to save data after %d attempts: %w", retryTimes, err)
		}

		time.Sleep(time.Duration(delayMs) * time.Millisecond)
	}

	return nil
}

// CreateKey creates a fully qualified storage key from prefix and key
//
// Parameters:
//   - uniquePrefix: The namespace prefix
//   - key: The key within the namespace
//
// Returns the combined key in format "prefix:key"
func CreateKey(uniquePrefix string, key string) string {
	return fmt.Sprintf("%s:%s", uniquePrefix, key)
}
