// Code generated by github.com/ONDC-Official/automation-validation-compiler, DO NOT EDIT.

package storageutils

import (
	"fmt"
	"validationpkg/validationutils"
)

// Store_select stores data from payload to storage for the select action
func Store_select(
	uniquePrefix string,
	payload interface{},
	store validationutils.StorageInterface,
	config StorageConfig,
) error {
	fmt.Printf("Stored data for action select successfully\n")
	return nil
}

// LoadFor_select loads stored data for the select action
func LoadFor_select(
	uniquePrefix string,
	store validationutils.StorageInterface,
) (validationutils.ExternalData, error) {
	result := validationutils.ExternalData{}

	fmt.Printf("Loaded external data for action select: %+v\n", result)
	return result, nil
}
