// Code generated by github.com/ONDC-Official/automation-validation-compiler, DO NOT EDIT.

package validationutils

import (
	"github.com/AsaiYusuke/jsonpath"
)

// isListOfStringsOrNull checks if the variable is a slice containing only strings or nil values
func isListOfStringsOrNull(variable interface{}) bool {
	slice, ok := variable.([]interface{})
	if !ok {
		return false
	}

	for _, item := range slice {
		if item == nil {
			continue
		}
		if _, isString := item.(string); !isString {
			return false
		}
	}
	return true
}

// GetJsonPath queries a payload using JSONPath and returns the results
func GetJsonPath(payload interface{}, path string, flattenResult bool) []interface{} {
	output, err := jsonpath.Retrieve(path, payload)
	if err != nil {
		return []interface{}{}
	}

	if isListOfStringsOrNull(output) {
		for i, item := range output {
			if item == nil {
				output[i] = "null"
			}
		}
	}

	if flattenResult {
		output = flattenSlice(output)
	}

	if len(output) == 0 {
		return []interface{}{}
	}
	return output
}

// flattenSlice recursively flattens nested slices
func flattenSlice(slice []interface{}) []interface{} {
	result := make([]interface{}, 0)
	for _, item := range slice {
		if nestedSlice, ok := item.([]interface{}); ok {
			result = append(result, flattenSlice(nestedSlice)...)
		} else {
			result = append(result, item)
		}
	}
	return result
}
