// Code generated by github.com/ONDC-Official/automation-validation-compiler, DO NOT EDIT.

package validationutils

// ValidationConfig holds configuration options for running validation routines.
type ValidationConfig struct {
	// StateFullValidations enables stateful validations that may depend on previous data
	StateFullValidations bool
	// UniqueKey is an optional unique key for the validation instance
	UniqueKey *string
	// Store is an optional implementation of StorageInterface for persisting data across validations
	Store StorageInterface
	// OnlyInvalid if true, only invalid results will be returned
	OnlyInvalid bool
	// HideParentErrors hides nested error details if set to true
	HideParentErrors bool
	// Debug enables debug mode for additional diagnostic information
	Debug bool
}

// ValidationOutput represents the output of a validation run.
// Each element corresponds to a single validation test result.
type ValidationOutput struct {
	// TestName is the name of the validation test
	TestName string `json:"testName"`
	// Valid indicates whether the test passed (true) or failed (false)
	Valid bool `json:"valid"`
	// Code is a numeric code representing the result or error type
	Code int `json:"code"`
	// Description provides additional details about the test result
	Description string `json:"description,omitempty"`
	// DebugInfo contains diagnostic information useful for debugging
	DebugInfo *DebugInfo `json:"_debugInfo,omitempty"`
}

// DebugInfo contains diagnostic information for validation results
type DebugInfo struct {
	// FedConfig is the configuration used to generate the validation
	FedConfig interface{} `json:"fedConfig"`
}

// ExternalData holds external data references for validation
type ExternalData struct {
	Self interface{} `json:"_SELF,omitempty"`
}

// ValidationInput represents the input data for validation functions
type ValidationInput struct {
	Payload      interface{}
	ExternalData ExternalData
	Config       ValidationConfig
}

// TestFunction is a function type that takes ValidationInput and returns a slice of ValidationOutput
type TestFunction func(input ValidationInput) ([]ValidationOutput, error)

// TestFunctionArray is a slice of test functions
type TestFunctionArray []TestFunction
